apiVersion: v1
kind: Namespace
metadata:
  name: datacore
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cds-operator
  namespace: datacore
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - "*"
        #  - cdscontroller.datacore.com
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cds-operator
  namespace: datacore
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cds-operator
  namespace: datacore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cds-operator
subjects:
- kind: ServiceAccount
  name: cds-operator
  namespace: datacore
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cds-operator
  namespace: datacore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cds-operator
    spec:
      serviceAccountName: cds-operator
      containers:
      - name: cds-operator
        image: datacoresoftware/cds-operator-0.1:v1alpha
        command: ["/cdsoperator"]
        args: 
        - --buildType=release 
        - --buildTag=v1alpha
      imagePullSecrets:
      - name: cds-docker-credentials

