apiVersion: cdscontroller.datacore.com/v1alpha1
kind: CDSVolume
metadata:
  name: wp-volume
spec:
  classname: iscsi-skeleton
  volumeid: wp-pv
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
